version: '3.8'

services:
  api1:
    image: service1_image  # используем собранный образ
    build:
      context: ./backend/services/service1 # место хранения файла контекста
    ports:
      - "8001:8001"
    networks:
      - mynetwork
  mainapp:
    build:
      context: ./backend  # Укажите путь к вашему mainapp.py (должен содержать Dockerfile)
    ports:
      - "8000:8000"  # Публичный порт для обращения к главному приложению
    depends_on:
      - api1  # Зависимость от api1, чтобы он запустился первым
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Монтирование Docker сокета
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge